---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: 127.0.0.1
  sudo: yes
  roles:
    - common

- name: configure postgresql stack on database nodes
  hosts: 127.0.0.1
  sudo: yes
  roles:
    - database
    
- name: configure odoo stack on odoo nodes
  hosts: 127.0.0.1
  sudo: yes
  roles:
    - odoo