# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network "forwarded_port", guest: 8090, host: 8069
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.ssh.forward_agent = true
  config.vm.synced_folder "./openerp-filetransfer", "/openerp_filetransfer", create: true

  #require 'rbconfig'
  #is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)
    #if is_windows
    #   Provisioning configuration for shell script. (Windows)
        config.vm.provision "shell" do |sh|
            sh.path = "provision/windows.sh"
            sh.args = "provision/playbook.yml provision/inventory"
        end
    #else
    #   Provisioning configuration for Ansible (for Mac/Linux hosts).
    #   config.vm.provision "ansible" do |ansible|
    #       ansible.playbook = "provision/playbook.yml"
    #       ansible.inventory_path = "provision/inventory"
    #       ansible.sudo = true
    #   end
end