# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.network "forwarded_port", guest:8069, host:8069
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"
  # config.ssh.forward_agent = true
  config.vm.synced_folder "./openerp-filetransfer", "/openerp_filetransfer", create: true

  config.vm.provision "docker" do |d|
    d.run "flox/ubuntu-openerp",
      args: "-d --name='openerp' --publish='8069:8069'"
  end
end